# version: 1.0.0 (Customized with Nerd Font Icons)

add_newline = false
continuation_prompt = "[▸▹ ](dimmed white)"

format = """($nix_shell$container$fill$git_metrics\n)$cmd_duration\
$hostname\
$localip\
$shlvl\
$shell\
$env_var\
$jobs\
$sudo\
$username\
$character"""

right_format = """
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$crystal\
$custom\
$status\
$os\
$battery\
$time"""

[fill]
symbol = ' '

[character]
format = "$symbol "
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"
vimcmd_symbol = "[N](bold green)"

[sudo]
format = "[$symbol]($style)"
style = "bold italic bright-purple"
symbol = "󰌆 "
disabled = false

[username]
style_user = "bright-yellow bold italic"
style_root = "purple bold italic"
format = "[󰀉 $user]($style) "
disabled = false
show_always = false

[directory]
home_symbol = " "
truncation_length = 2
truncation_symbol = "󰉋 "
read_only = " 󰌾"
use_os_path_sep = true
style = "italic blue"
format = '[$path]($style)[$read_only]($read_only_style)'
repo_root_style = 'bold blue'
# Ícone de branch/repo trocado para o oficial do git
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) [󰊢 ](bold bright-blue)'

[git_branch]
format = " [$symbol$branch(:$remote_branch)]($style)"
symbol = "󰊢 "
style = "italic bright-blue"
truncation_symbol = "⋯"
truncation_length = 11
ignore_branches = ["main", "master"]
only_attached = true

[git_status]
style = "bold italic bright-blue"
format = "([⎪$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed⎥]($style))"
conflicted = "󰞇 "
ahead = "⇡ "
behind = "⇣ "
untracked = "? "
stashed = "󰏗 "
modified = "󰏫 "
staged = "󰔓 "
renamed = "󰔓 "
deleted = "󰆴 "

[nodejs]
format = " [node](italic) [󰎙 ($version)](bold bright-green)"
version_format = "${raw}"
detect_files = ["package-lock.json", "yarn.lock"]
detect_folders = ["node_modules"]

[docker_context]
symbol = "󰡨 "
format = " docker [$symbol$context]($style)"

[python]
format = " [py](italic) [${symbol}${version}]($style)"
symbol = "󱔎 "
version_format = "${raw}"
style = "bold bright-yellow"

[rust]
format = " [rs](italic) [$symbol$version]($style)"
symbol = "󱘗 "
version_format = "${raw}"
style = "bold red"

[package]
format = " [pkg](italic dimmed) [$symbol$version]($style)"
version_format = "${raw}"
symbol = "󰏗 "
style = "dimmed yellow italic bold"
